import '../models/surah.dart';

class QuranDataService {
  // List of all 114 Surahs with their details
  static const List<Surah> surahs = [
    Surah(number: 1, nameArabic: 'الفاتحة', nameEnglish: 'The Opening', transliteration: 'Al-Fatihah', numberOfAyahs: 7),
    Surah(number: 2, nameArabic: 'البقرة', nameEnglish: 'The Cow', transliteration: 'Al-Baqarah', numberOfAyahs: 286),
    Surah(number: 3, nameArabic: 'آل عمران', nameEnglish: 'The Family of Imran', transliteration: 'Al-Imran', numberOfAyahs: 200),
    Surah(number: 4, nameArabic: 'النساء', nameEnglish: 'The Women', transliteration: 'An-Nisa', numberOfAyahs: 176),
    Surah(number: 5, nameArabic: 'المائدة', nameEnglish: 'The Table Spread', transliteration: 'Al-Maidah', numberOfAyahs: 120),
    Surah(number: 6, nameArabic: 'الأنعام', nameEnglish: 'The Cattle', transliteration: 'Al-Anam', numberOfAyahs: 165),
    Surah(number: 7, nameArabic: 'الأعراف', nameEnglish: 'The Heights', transliteration: 'Al-Araf', numberOfAyahs: 206),
    Surah(number: 8, nameArabic: 'الأنفال', nameEnglish: 'The Spoils of War', transliteration: 'Al-Anfal', numberOfAyahs: 75),
    Surah(number: 9, nameArabic: 'التوبة', nameEnglish: 'The Repentance', transliteration: 'At-Tawbah', numberOfAyahs: 129),
    Surah(number: 10, nameArabic: 'يونس', nameEnglish: 'Jonah', transliteration: 'Yunus', numberOfAyahs: 109),
    Surah(number: 11, nameArabic: 'هود', nameEnglish: 'Hud', transliteration: 'Hud', numberOfAyahs: 123),
    Surah(number: 12, nameArabic: 'يوسف', nameEnglish: 'Joseph', transliteration: 'Yusuf', numberOfAyahs: 111),
    Surah(number: 13, nameArabic: 'الرعد', nameEnglish: 'The Thunder', transliteration: 'Ar-Rad', numberOfAyahs: 43),
    Surah(number: 14, nameArabic: 'إبراهيم', nameEnglish: 'Abraham', transliteration: 'Ibrahim', numberOfAyahs: 52),
    Surah(number: 15, nameArabic: 'الحجر', nameEnglish: 'The Rocky Tract', transliteration: 'Al-Hijr', numberOfAyahs: 99),
    Surah(number: 16, nameArabic: 'النحل', nameEnglish: 'The Bee', transliteration: 'An-Nahl', numberOfAyahs: 128),
    Surah(number: 17, nameArabic: 'الإسراء', nameEnglish: 'The Night Journey', transliteration: 'Al-Isra', numberOfAyahs: 111),
    Surah(number: 18, nameArabic: 'الكهف', nameEnglish: 'The Cave', transliteration: 'Al-Kahf', numberOfAyahs: 110),
    Surah(number: 19, nameArabic: 'مريم', nameEnglish: 'Mary', transliteration: 'Maryam', numberOfAyahs: 98),
    Surah(number: 20, nameArabic: 'طه', nameEnglish: 'Ta-Ha', transliteration: 'Ta-Ha', numberOfAyahs: 135),
    Surah(number: 21, nameArabic: 'الأنبياء', nameEnglish: 'The Prophets', transliteration: 'Al-Anbiya', numberOfAyahs: 112),
    Surah(number: 22, nameArabic: 'الحج', nameEnglish: 'The Pilgrimage', transliteration: 'Al-Hajj', numberOfAyahs: 78),
    Surah(number: 23, nameArabic: 'المؤمنون', nameEnglish: 'The Believers', transliteration: 'Al-Muminun', numberOfAyahs: 118),
    Surah(number: 24, nameArabic: 'النور', nameEnglish: 'The Light', transliteration: 'An-Nur', numberOfAyahs: 64),
    Surah(number: 25, nameArabic: 'الفرقان', nameEnglish: 'The Criterion', transliteration: 'Al-Furqan', numberOfAyahs: 77),
    Surah(number: 26, nameArabic: 'الشعراء', nameEnglish: 'The Poets', transliteration: 'Ash-Shuara', numberOfAyahs: 227),
    Surah(number: 27, nameArabic: 'النمل', nameEnglish: 'The Ant', transliteration: 'An-Naml', numberOfAyahs: 93),
    Surah(number: 28, nameArabic: 'القصص', nameEnglish: 'The Stories', transliteration: 'Al-Qasas', numberOfAyahs: 88),
    Surah(number: 29, nameArabic: 'العنكبوت', nameEnglish: 'The Spider', transliteration: 'Al-Ankabut', numberOfAyahs: 69),
    Surah(number: 30, nameArabic: 'الروم', nameEnglish: 'The Romans', transliteration: 'Ar-Rum', numberOfAyahs: 60),
    Surah(number: 31, nameArabic: 'لقمان', nameEnglish: 'Luqman', transliteration: 'Luqman', numberOfAyahs: 34),
    Surah(number: 32, nameArabic: 'السجدة', nameEnglish: 'The Prostration', transliteration: 'As-Sajdah', numberOfAyahs: 30),
    Surah(number: 33, nameArabic: 'الأحزاب', nameEnglish: 'The Combined Forces', transliteration: 'Al-Ahzab', numberOfAyahs: 73),
    Surah(number: 34, nameArabic: 'سبأ', nameEnglish: 'Sheba', transliteration: 'Saba', numberOfAyahs: 54),
    Surah(number: 35, nameArabic: 'فاطر', nameEnglish: 'The Originator', transliteration: 'Fatir', numberOfAyahs: 45),
    Surah(number: 36, nameArabic: 'يس', nameEnglish: 'Ya-Sin', transliteration: 'Ya-Sin', numberOfAyahs: 83),
    Surah(number: 37, nameArabic: 'الصافات', nameEnglish: 'Those Ranges in Ranks', transliteration: 'As-Saffat', numberOfAyahs: 182),
    Surah(number: 38, nameArabic: 'ص', nameEnglish: 'Sad', transliteration: 'Sad', numberOfAyahs: 88),
    Surah(number: 39, nameArabic: 'الزمر', nameEnglish: 'The Groups', transliteration: 'Az-Zumar', numberOfAyahs: 75),
    Surah(number: 40, nameArabic: 'غافر', nameEnglish: 'The Forgiver', transliteration: 'Ghafir', numberOfAyahs: 85),
    Surah(number: 41, nameArabic: 'فصلت', nameEnglish: 'Explained in Detail', transliteration: 'Fussilat', numberOfAyahs: 54),
    Surah(number: 42, nameArabic: 'الشورى', nameEnglish: 'The Consultation', transliteration: 'Ash-Shura', numberOfAyahs: 53),
    Surah(number: 43, nameArabic: 'الزخرف', nameEnglish: 'The Gold Adornments', transliteration: 'Az-Zukhruf', numberOfAyahs: 89),
    Surah(number: 44, nameArabic: 'الدخان', nameEnglish: 'The Smoke', transliteration: 'Ad-Dukhan', numberOfAyahs: 59),
    Surah(number: 45, nameArabic: 'الجاثية', nameEnglish: 'The Kneeling', transliteration: 'Al-Jathiyah', numberOfAyahs: 37),
    Surah(number: 46, nameArabic: 'الأحقاف', nameEnglish: 'The Wind-Curved Sandhills', transliteration: 'Al-Ahqaf', numberOfAyahs: 35),
    Surah(number: 47, nameArabic: 'محمد', nameEnglish: 'Muhammad', transliteration: 'Muhammad', numberOfAyahs: 38),
    Surah(number: 48, nameArabic: 'الفتح', nameEnglish: 'The Victory', transliteration: 'Al-Fath', numberOfAyahs: 29),
    Surah(number: 49, nameArabic: 'الحجرات', nameEnglish: 'The Rooms', transliteration: 'Al-Hujurat', numberOfAyahs: 18),
    Surah(number: 50, nameArabic: 'ق', nameEnglish: 'Qaf', transliteration: 'Qaf', numberOfAyahs: 45),
    Surah(number: 51, nameArabic: 'الذاريات', nameEnglish: 'The Winnowing Winds', transliteration: 'Adh-Dhariyat', numberOfAyahs: 60),
    Surah(number: 52, nameArabic: 'الطور', nameEnglish: 'The Mount', transliteration: 'At-Tur', numberOfAyahs: 49),
    Surah(number: 53, nameArabic: 'النجم', nameEnglish: 'The Star', transliteration: 'An-Najm', numberOfAyahs: 62),
    Surah(number: 54, nameArabic: 'القمر', nameEnglish: 'The Moon', transliteration: 'Al-Qamar', numberOfAyahs: 55),
    Surah(number: 55, nameArabic: 'الرحمن', nameEnglish: 'The Most Merciful', transliteration: 'Ar-Rahman', numberOfAyahs: 78),
    Surah(number: 56, nameArabic: 'الواقعة', nameEnglish: 'The Inevitable', transliteration: 'Al-Waqiah', numberOfAyahs: 96),
    Surah(number: 57, nameArabic: 'الحديد', nameEnglish: 'The Iron', transliteration: 'Al-Hadid', numberOfAyahs: 29),
    Surah(number: 58, nameArabic: 'المجادلة', nameEnglish: 'The Pleading Woman', transliteration: 'Al-Mujadilah', numberOfAyahs: 22),
    Surah(number: 59, nameArabic: 'الحشر', nameEnglish: 'The Exile', transliteration: 'Al-Hashr', numberOfAyahs: 24),
    Surah(number: 60, nameArabic: 'الممتحنة', nameEnglish: 'The Examined One', transliteration: 'Al-Mumtahanah', numberOfAyahs: 13),
    Surah(number: 61, nameArabic: 'الصف', nameEnglish: 'The Ranks', transliteration: 'As-Saff', numberOfAyahs: 14),
    Surah(number: 62, nameArabic: 'الجمعة', nameEnglish: 'The Friday', transliteration: 'Al-Jumuah', numberOfAyahs: 11),
    Surah(number: 63, nameArabic: 'المنافقون', nameEnglish: 'The Hypocrites', transliteration: 'Al-Munafiqun', numberOfAyahs: 11),
    Surah(number: 64, nameArabic: 'التغابن', nameEnglish: 'The Mutual Disillusion', transliteration: 'At-Taghabun', numberOfAyahs: 18),
    Surah(number: 65, nameArabic: 'الطلاق', nameEnglish: 'The Divorce', transliteration: 'At-Talaq', numberOfAyahs: 12),
    Surah(number: 66, nameArabic: 'التحريم', nameEnglish: 'The Prohibition', transliteration: 'At-Tahrim', numberOfAyahs: 12),
    Surah(number: 67, nameArabic: 'الملك', nameEnglish: 'The Sovereignty', transliteration: 'Al-Mulk', numberOfAyahs: 30),
    Surah(number: 68, nameArabic: 'القلم', nameEnglish: 'The Pen', transliteration: 'Al-Qalam', numberOfAyahs: 52),
    Surah(number: 69, nameArabic: 'الحاقة', nameEnglish: 'The Reality', transliteration: 'Al-Haqqah', numberOfAyahs: 52),
    Surah(number: 70, nameArabic: 'المعارج', nameEnglish: 'The Ascending Stairways', transliteration: 'Al-Maarij', numberOfAyahs: 44),
    Surah(number: 71, nameArabic: 'نوح', nameEnglish: 'Noah', transliteration: 'Nuh', numberOfAyahs: 28),
    Surah(number: 72, nameArabic: 'الجن', nameEnglish: 'The Jinn', transliteration: 'Al-Jinn', numberOfAyahs: 28),
    Surah(number: 73, nameArabic: 'المزمل', nameEnglish: 'The Enshrouded One', transliteration: 'Al-Muzzammil', numberOfAyahs: 20),
    Surah(number: 74, nameArabic: 'المدثر', nameEnglish: 'The Cloaked One', transliteration: 'Al-Muddaththir', numberOfAyahs: 56),
    Surah(number: 75, nameArabic: 'القيامة', nameEnglish: 'The Resurrection', transliteration: 'Al-Qiyamah', numberOfAyahs: 40),
    Surah(number: 76, nameArabic: 'الإنسان', nameEnglish: 'The Man', transliteration: 'Al-Insan', numberOfAyahs: 31),
    Surah(number: 77, nameArabic: 'المرسلات', nameEnglish: 'Those Sent Forth', transliteration: 'Al-Mursalat', numberOfAyahs: 50),
    Surah(number: 78, nameArabic: 'النبأ', nameEnglish: 'The Tidings', transliteration: 'An-Naba', numberOfAyahs: 40),
    Surah(number: 79, nameArabic: 'النازعات', nameEnglish: 'Those Who Pull Out', transliteration: 'An-Naziat', numberOfAyahs: 46),
    Surah(number: 80, nameArabic: 'عبس', nameEnglish: 'He Frowned', transliteration: 'Abasa', numberOfAyahs: 42),
    Surah(number: 81, nameArabic: 'التكوير', nameEnglish: 'The Overthrowing', transliteration: 'At-Takwir', numberOfAyahs: 29),
    Surah(number: 82, nameArabic: 'الانفطار', nameEnglish: 'The Cleaving', transliteration: 'Al-Infitar', numberOfAyahs: 19),
    Surah(number: 83, nameArabic: 'المطففين', nameEnglish: 'The Defrauding', transliteration: 'Al-Mutaffifin', numberOfAyahs: 36),
    Surah(number: 84, nameArabic: 'الانشقاق', nameEnglish: 'The Splitting Open', transliteration: 'Al-Inshiqaq', numberOfAyahs: 25),
    Surah(number: 85, nameArabic: 'البروج', nameEnglish: 'The Mansions of the Stars', transliteration: 'Al-Buruj', numberOfAyahs: 22),
    Surah(number: 86, nameArabic: 'الطارق', nameEnglish: 'The Nightcomer', transliteration: 'At-Tariq', numberOfAyahs: 17),
    Surah(number: 87, nameArabic: 'الأعلى', nameEnglish: 'The Most High', transliteration: 'Al-Ala', numberOfAyahs: 19),
    Surah(number: 88, nameArabic: 'الغاشية', nameEnglish: 'The Overwhelming', transliteration: 'Al-Ghashiyah', numberOfAyahs: 26),
    Surah(number: 89, nameArabic: 'الفجر', nameEnglish: 'The Dawn', transliteration: 'Al-Fajr', numberOfAyahs: 30),
    Surah(number: 90, nameArabic: 'البلد', nameEnglish: 'The City', transliteration: 'Al-Balad', numberOfAyahs: 20),
    Surah(number: 91, nameArabic: 'الشمس', nameEnglish: 'The Sun', transliteration: 'Ash-Shams', numberOfAyahs: 15),
    Surah(number: 92, nameArabic: 'الليل', nameEnglish: 'The Night', transliteration: 'Al-Layl', numberOfAyahs: 21),
    Surah(number: 93, nameArabic: 'الضحى', nameEnglish: 'The Morning Hours', transliteration: 'Ad-Duha', numberOfAyahs: 11),
    Surah(number: 94, nameArabic: 'الشرح', nameEnglish: 'The Relief', transliteration: 'Ash-Sharh', numberOfAyahs: 8),
    Surah(number: 95, nameArabic: 'التين', nameEnglish: 'The Fig', transliteration: 'At-Tin', numberOfAyahs: 8),
    Surah(number: 96, nameArabic: 'العلق', nameEnglish: 'The Clot', transliteration: 'Al-Alaq', numberOfAyahs: 19),
    Surah(number: 97, nameArabic: 'القدر', nameEnglish: 'The Power', transliteration: 'Al-Qadr', numberOfAyahs: 5),
    Surah(number: 98, nameArabic: 'البينة', nameEnglish: 'The Clear Proof', transliteration: 'Al-Bayyinah', numberOfAyahs: 8),
    Surah(number: 99, nameArabic: 'الزلزلة', nameEnglish: 'The Earthquake', transliteration: 'Az-Zalzalah', numberOfAyahs: 8),
    Surah(number: 100, nameArabic: 'العاديات', nameEnglish: 'The Courser', transliteration: 'Al-Adiyat', numberOfAyahs: 11),
    Surah(number: 101, nameArabic: 'القارعة', nameEnglish: 'The Calamity', transliteration: 'Al-Qariah', numberOfAyahs: 11),
    Surah(number: 102, nameArabic: 'التكاثر', nameEnglish: 'The Rivalry in World Increase', transliteration: 'At-Takathur', numberOfAyahs: 8),
    Surah(number: 103, nameArabic: 'العصر', nameEnglish: 'The Declining Day', transliteration: 'Al-Asr', numberOfAyahs: 3),
    Surah(number: 104, nameArabic: 'الهمزة', nameEnglish: 'The Traducer', transliteration: 'Al-Humazah', numberOfAyahs: 9),
    Surah(number: 105, nameArabic: 'الفيل', nameEnglish: 'The Elephant', transliteration: 'Al-Fil', numberOfAyahs: 5),
    Surah(number: 106, nameArabic: 'قريش', nameEnglish: 'Quraysh', transliteration: 'Quraysh', numberOfAyahs: 4),
    Surah(number: 107, nameArabic: 'الماعون', nameEnglish: 'The Small Kindnesses', transliteration: 'Al-Maun', numberOfAyahs: 7),
    Surah(number: 108, nameArabic: 'الكوثر', nameEnglish: 'The Abundance', transliteration: 'Al-Kawthar', numberOfAyahs: 3),
    Surah(number: 109, nameArabic: 'الكافرون', nameEnglish: 'The Disbelievers', transliteration: 'Al-Kafirun', numberOfAyahs: 6),
    Surah(number: 110, nameArabic: 'النصر', nameEnglish: 'The Divine Support', transliteration: 'An-Nasr', numberOfAyahs: 3),
    Surah(number: 111, nameArabic: 'المسد', nameEnglish: 'The Palm Fiber', transliteration: 'Al-Masad', numberOfAyahs: 5),
    Surah(number: 112, nameArabic: 'الإخلاص', nameEnglish: 'The Sincerity', transliteration: 'Al-Ikhlas', numberOfAyahs: 4),
    Surah(number: 113, nameArabic: 'الفلق', nameEnglish: 'The Daybreak', transliteration: 'Al-Falaq', numberOfAyahs: 5),
    Surah(number: 114, nameArabic: 'الناس', nameEnglish: 'Mankind', transliteration: 'An-Nas', numberOfAyahs: 6),
  ];

  static Surah? getSurahByNumber(int number) {
    try {
      return surahs.firstWhere((surah) => surah.number == number);
    } catch (e) {
      return null;
    }
  }

  static List<Surah> getAllSurahs() {
    return List.from(surahs);
  }
}
